[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer_runs = 800
fs_permissions = [{ access = "read", path = "./" }]
gas_reports = ["*"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_ETHEREUM}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
